# Generated by Django 4.0.4 on 2022-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(null=True, upload_to='companyprofile'),
        ),
    ]
