# Generated by Django 4.0.4 on 2022-06-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_companyprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
